#cloud-config

hostname: $HOSTNAME
ssh_authorized_keys:
  - $PUBKEY

coreos:
  update:
    reboot-strategy: off
  units:
    - name: "00-eno1.network"
      runtime: true
      content: |
          [Match]
          Name=eno1

          [Network]
          Address=172.17.8.20/24
          Gateway=172.17.8.20
          #Address=192.168.178.210
          #Gateway=192.168.178.1
          #DNS=192.168.178.1
          IPForward=yes

    - name: "systemd-networkd-wait-online.service"
      command: start

    - name: "setup-env.service"
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Setup environment with proper public/private IPv4 addresses
        Before=etcd2.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/share/oem/setup-env.sh

    - name: "oem-cloudinit.service"
      command: start
      runtime: true
      content: |
          [Unit]
          Description=call cloud-init for our 2nd-stage user data configuration
          After=setup-env.service

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          EnvironmentFile=/etc/environment
          ExecStart=/usr/bin/coreos-cloudinit --from-file=/usr/share/oem/cloud-config-2nd-stage.yml

###EOF###
